### ISSUE TITLE
style config options are not working

### ISSUE THREAD

**Issue by kkirankk** [dgox16/oldworld.nvim#1]
Configuring style not working.

        {
                "dgox16/oldworld.nvim",
                lazy = false,
                priority = 1000,
                config = function(opts)
                        require("oldworld").setup({
                                styles = {
                                        functions = { italic = false},
                                },
                        })
                        vim.cmd [[ colorscheme oldworld ]]
                end
        }

**Comment by dgox16** [comment]
Thank you for the feedback. I've already fixed it. I had a flaw when setting default styles. From now on, all styles are disabled by default, and you can choose which ones to activate. In your case, it's not necessary to disable the style for functions now, but to achieve the previous design, you may want to enable italics in comments again.
