### ISSUE TITLE
feature request: add highlights for semantic highlights and so on...

### ISSUE THREAD

**Issue by Peeeaje** [dgox16/oldworld.nvim#3]
First of all, thanks for creating the theme. I am really enjoying to use neovim with oldworld.nvim.

What I found using the theme is that when I am using pyright (basedpyright) constants are not colored as red.
It seems semantic highlight has higher priority than treesitter so the color gets disabled.
![image](https://github.com/dgox16/oldworld.nvim/assets/74146834/d7582f66-a3b0-4703-9e0b-dd15b6495253)

if this is not intentional and you think it doesn't have bad side effect adding below would be awesome at least for me.
```
["@lsp.mod.readonly"] = { fg = p.red },
```

Also, in python the `def` is not colored. I thought it is intentional but I want to confirm after I realized above problem. Thanks in advance :)
![image](https://github.com/dgox16/oldworld.nvim/assets/74146834/bcf4c25f-b76e-49bd-abfb-d4e1aa1921c5)

**Comment by dgox16** [comment]
Hello, Greetings. Thank you for using oldworld. I apologize for the inconvenience. The way I am using the theme is with Rust, and I still need to improve the colors for other languages. 

Regarding the constants, you are right, the constants are in red, so I will fix that shortly. 

On the other hand, the color of the dedicated keywords (fn, def, function, etc.) is intended to be white, but I have reviewed options to assign a different color, although I haven't decided yet.

**Comment by Peeeaje** [comment]
@dgox16 
Thanks for the quick fixing!! 

This is your theme so I don't mind if `def` or `function` got colored or not.
